
spring:
  datasource:
    username: spi
    password: spi
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jpa-poc-test
  h2:
    console:
      enabled: true
      

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
logging:
  level:
    org:
      hibernate:
        type: trace
